# Stage 1: Build Vite app
FROM node:18-alpine AS builder
WORKDIR /app

# Copy package.json & lock file
COPY package*.json ./

# Cài dependencies
RUN npm ci

# Copy toàn bộ source code
COPY . .

# Build Vite (kết quả ra thư mục dist/)
RUN npm run build


# Stage 2: Serve bằng Nginx
FROM nginx:alpine

# Copy build từ stage builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy file config nginx (SPA fallback)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
